=== PedestrianDynamics/jupedsim/jpsreport/xsd/jps_report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="JPSreport">
    <xs:complexType>
      <xs:all>
        <xs:element name="geometry">
          <xs:annotation>
            <xs:documentation>geometry file</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="file" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>

        <xs:element name="logfile">
          <xs:annotation>
            <xs:documentation>logfile file</xs:documentation>
          </xs:annotation>
        </xs:element>

        <xs:element name="trajectories">
          <xs:annotation>
            <xs:documentation>trajectories file and format either a file name or a path location. In the latter case all files in the directory will be used.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="file" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="name" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="path">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="location" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="format" use="required"/>
            <xs:attribute type="xs:string" name="unit" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="output">
          <xs:annotation>
            <xs:documentation>give relative path based on the location inifile or give the absolute path.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="location" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="measurement_areas">
          <xs:annotation>
            <xs:documentation>Define the measurement areas will be used.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="area_B" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="vertex" maxOccurs="unbounded" minOccurs="4">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="x"  use="optional"/>
                            <xs:attribute type="xs:float" name="y"  use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="length_in_movement_direction" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="distance" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="id" use="required"/>
                  <xs:attribute type="xs:string" name="type" use="optional"/>
                  <xs:attribute type="xs:float" name="zPos" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="area_L" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="start">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="x" use="required"/>
                            <xs:attribute type="xs:float" name="y" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="end">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="x" use="required"/>
                            <xs:attribute type="xs:float" name="y" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="id" use="required"/>
                  <xs:attribute type="xs:string" name="type" use="optional"/>
                  <xs:attribute type="xs:float" name="zPos" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="unit" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="velocity">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="set_movement_direction"/>
              <xs:element type="xs:string" name="ignore_backward_movement"/>
              <xs:element type="xs:int" name="frame_step">
                <xs:annotation>
                  <xs:documentation>half of the time interval that used to calculate instantaneous velocity 
         of ped i [fr] here v_i = (X(t+deltaF) - X(t+deltaF))/(2*deltaF). X is location.</xs:documentation>
                </xs:annotation>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="method_A">
          <xs:annotation>
            <xs:documentation>Method A (Zhang2011a) flow and velocity</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="frame_interval" >
                <xs:annotation>
                  <xs:documentation>Time interval used to count the flow [fr]</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:int" >
                      <xs:attribute type="xs:string" name="unit"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="measurement_area" maxOccurs="unbounded" minOccurs="1">
                <xs:annotation>
                  <xs:documentation>The coordinate of the line used to calculate the flow and velocity</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="id"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="enabled"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="method_B">
          <xs:annotation>
            <xs:documentation>Method B (Zhang2011a) density and velocity based on T_in and T_out</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="measurement_area" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="id"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="enabled"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="method_C">
          <xs:annotation>
            <xs:documentation>Method C (Zhang2011a) Classical density and velocity</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="measurement_area" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="id"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="enabled"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="method_D">
          <xs:annotation>
            <xs:documentation>Method D (Zhang2011a) Voronoi density and velocity</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="measurement_area" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="id"  use="required"/>
                      <xs:attribute type="xs:int" name="start_frame"  use="required"/>
                      <xs:attribute type="xs:int" name="stop_frame"  use="required"/>
                      <xs:attribute type="xs:string" name="get_individual_FD"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="one_dimensional">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="enabled"   use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="cut_by_circle">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="enabled"   use="required"/>
                      <xs:attribute type="xs:double" name="radius"  use="required"/>
                      <xs:attribute type="xs:int" name="edges"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="profiles">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="enabled"  use="required"/>
                      <xs:attribute type="xs:float" name="grid_size_x"  use="required"/>
                      <xs:attribute type="xs:float" name="grid_size_y"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="enabled"  use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="method_I">
          <xs:annotation>
            <xs:documentation>Method I individual Voronoi density and velocity</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="measurement_area" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="id"  use="required"/>
                      <xs:attribute type="xs:int" name="start_frame"  use="required"/>
                      <xs:attribute type="xs:int" name="stop_frame"  use="required"/>
                      <xs:attribute type="xs:string" name="get_individual_FD"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="one_dimensional">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="enabled"   use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="cut_by_circle">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="enabled"   use="required"/>
                      <xs:attribute type="xs:double" name="radius"  use="required"/>
                      <xs:attribute type="xs:int" name="edges"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="enabled"  use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="method_J">
          <xs:annotation>
            <xs:documentation>Method Voronoi density and velocity</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="measurement_area" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:int" name="id"  use="required"/>
                      <xs:attribute type="xs:int" name="start_frame"  use="required"/>
                      <xs:attribute type="xs:int" name="stop_frame"  use="required"/>
                      <xs:attribute type="xs:string" name="get_individual_FD"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="one_dimensional">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="enabled"   use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="cut_by_circle">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="enabled"   use="required"/>
                      <xs:attribute type="xs:double" name="radius"  use="required"/>
                      <xs:attribute type="xs:int" name="edges"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="profiles">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="enabled"  use="required"/>
                      <xs:attribute type="xs:float" name="grid_size_x"  use="required"/>
                      <xs:attribute type="xs:float" name="grid_size_y"  use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="enabled"  use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:all>
      <xs:attribute type="xs:string" name="project"  use="required"/>
      <xs:attribute name="version" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="0.8.5" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== PedestrianDynamics/jupedsim/systemtest/jpsreport_tests/method_A/test3/jpsreport_ini.xml
<?xml version="1.0" encoding="UTF-8"?>
<JPSreport project="JPS-Project" version="0.8.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/jps_report.xsd">
  <geometry file = "geometry.xml" />
  <logfile>logfile_Method_A.txt</logfile>
  <trajectories format="txt" unit="m">
    <file name="traj.txt" />
  </trajectories>
  <output location="Output"/>
  
  <measurement_areas unit="m">
    <area_L id="9" type="Line" zPos="None">
      <end x="9.0" y="0.0" />
      <start x="9.0" y="2.0" />
    </area_L>
    <area_L id="7" type="Line" zPos="None">
      <end x="7.0" y="0.0" />
      <start x="7.0" y="2.0" />
    </area_L>
  </measurement_areas>

  <velocity frame_step="10" set_movement_direction="None" ignore_backward_movement="false"/>

  <method_A enabled="true">
    <measurement_area id="9" frame_interval="2"/>
    <measurement_area id="7" frame_interval="2"/>
  </method_A>
</JPSreport>

=== PedestrianDynamics/jupedsim/jpsreport/demos/crossing/ini_crossing_90_c_6_v5.xml
<?xml version="1.0" encoding="UTF-8"?>
<JPSreport project="crossing_90_c_6_v5" version="0.8.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/jps_report.xsd">

    <geometry file = "geo_crossing_90_c_6_v5.xml" />

    <logfile>log_crossing_90_c_6_v5.txt</logfile>

    <output location="crossing_90_c_6_v5_Output/" />

    <trajectories format="txt" unit="m"> 
        <file name="traj_crossing_90_c_6_v5.txt" /> 
        <path location="./" /> 
    </trajectories> 


    <measurement_areas unit="m"> 
        <area_B id="1" type="BoundingBox" zPos="None"> 
            <vertex x="0.00" y="0.00" /> 
            <vertex x="0.00" y="4.00" /> 
            <vertex x="4.00" y="4.00" /> 
            <vertex x="4.00" y="0.00" /> 
            <length_in_movement_direction distance="4.0" /> 
        </area_B> 
        <area_L id="2" type="Line" zPos="None"> 
            <start x="4" y="0" /> 
            <end x="4" y="4" /> 
        </area_L> 
    </measurement_areas> 

    <velocity frame_step="10" set_movement_direction="None" ignore_backward_movement="false"/>

    <method_A enabled="true">
        <measurement_area id="2" frame_interval="100"/>
    </method_A> 

    <method_B enabled="false">
        <measurement_area id="1" /> 
    </method_B> 

    <method_C enabled="true">
        <measurement_area id="1" />
    </method_C> 

	<method_D enabled="true">
        <measurement_area id="1" start_frame="None" stop_frame="None" get_individual_FD="false"/>
		<one_dimensional enabled="false"/>
        <cut_by_circle enabled="false" radius="1.0" edges="10"/>
        <profiles enabled="false" grid_size_x="0.20" grid_size_y="0.20"/> 
    </method_D>

</JPSreport>
