=== PedestrianDynamics/jupedsim/xsd/jps_geometry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="geometry">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="rooms" maxOccurs="1" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="room" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="subroom" maxOccurs="unbounded" minOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="polygon" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="vertex" maxOccurs="unbounded" minOccurs="0">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:float" name="px" use="required" />
                                        <xs:attribute type="xs:float" name="py" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="caption" use="required" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="obstacle" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="polygon">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="vertex" maxOccurs="unbounded" minOccurs="0">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                              <xs:attribute type="xs:float" name="px" use="required" />
                                              <xs:attribute type="xs:float" name="py" use="required" />
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="caption" use="optional" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:int" name="id" use="required" />
                              <xs:attribute type="xs:string" name="caption" use="optional" />
                              <xs:attribute type="xs:float" name="height" use="optional" />
                              <xs:attribute type="xs:int" name="closed" use="optional" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="up" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:float" name="px" use="required" />
                                  <xs:attribute type="xs:byte" name="py" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="down" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:float" name="px" use="required" />
                                  <xs:attribute type="xs:byte" name="py" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:int" name="id" use="required" />
                        <xs:attribute type="xs:string" name="caption" use="optional" />
                        <xs:attribute type="xs:float" name="A_x" use="optional" />
                        <xs:attribute type="xs:float" name="B_y" use="optional" />
                        <xs:attribute type="xs:float" name="C" use="optional" />
                        <xs:attribute name="class" use="required">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="stair" />
                              <xs:enumeration value="subroom" />
                              <xs:enumeration value="floor" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="crossings" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="crossing" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="vertex" maxOccurs="unbounded" minOccurs="0">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:float" name="px" use="required" />
                                        <xs:attribute type="xs:float" name="py" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:int" name="id" use="required" />
                              <xs:attribute type="xs:int" name="subroom1_id" use="required" />
                              <xs:attribute type="xs:int" name="subroom2_id" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="id" use="required" />
                  <xs:attribute type="xs:string" name="caption" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="transitions">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="transition" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="vertex" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="px" use="required" />
                            <xs:attribute type="xs:float" name="py" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="id" use="required" />
                  <xs:attribute type="xs:string" name="caption" use="required" />
                  <xs:attribute type="xs:string" name="type" use="optional" />
                  <xs:attribute type="xs:int" name="room1_id" use="required" />
                  <xs:attribute type="xs:int" name="subroom1_id" use="required" />
                  <xs:attribute type="xs:int" name="room2_id" use="required" />
                  <xs:attribute type="xs:int" name="subroom2_id" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="caption" use="required" />
      <xs:attribute name="version" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:float">
            <xs:enumeration value="0.8" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="unit" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="m" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== PedestrianDynamics/jupedsim/docs/notebooks/files/geometry.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<geometry version="0.8" caption="corner" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xsd.jupedsim.org/jps_geometry.xsd" unit="m">
  <rooms>
    <room id="0" caption="floor">
      <subroom id="1" caption="Room 1" class="Not specified" A_x="0" B_y="0" C_z="0">
        <polygon caption="wall">
          <vertex px="0" py="5"/>
          <vertex px="0" py="0"/>
        </polygon>
        <polygon caption="wall">
          <vertex px="4" py="5"/>
          <vertex px="4" py="4"/>
        </polygon>
        <polygon caption="wall">
          <vertex px="4" py="3"/>
          <vertex px="4" py="2"/>
        </polygon>
        <polygon caption="wall">
          <vertex px="4" py="1"/>
          <vertex px="4" py="0"/>
        </polygon>
        <polygon caption="wall">
          <vertex px="0" py="5"/>
          <vertex px="4" py="5"/>
        </polygon>
        <polygon caption="wall">
          <vertex px="4" py="0"/>
          <vertex px="0" py="0"/>
        </polygon>
        <obstacle id="0" caption="Obstacle 0" closed="1">
          <polygon>
            <vertex px="1" py="1.5"/>
            <vertex px="1.5" py="1.5"/>
          </polygon>
          <polygon>
            <vertex px="1.5" py="1"/>
            <vertex px="1.5" py="1.5"/>
          </polygon>
          <polygon>
            <vertex px="1" py="1.5"/>
            <vertex px="1" py="1"/>
          </polygon>
          <polygon>
            <vertex px="1" py="1"/>
            <vertex px="1.5" py="1"/>
          </polygon>
        </obstacle>
        <obstacle id="1" caption="Obstacle 1" closed="1">
          <polygon>
            <vertex px="2" py="4"/>
            <vertex px="2.5" py="4"/>
          </polygon>
          <polygon>
            <vertex px="2" py="4"/>
            <vertex px="2" py="3.5"/>
          </polygon>
          <polygon>
            <vertex px="2" py="3.5"/>
            <vertex px="2.5" py="3.5"/>
          </polygon>
          <polygon>
            <vertex px="2.5" py="4"/>
            <vertex px="2.5" py="3.5"/>
          </polygon>
        </obstacle>
      </subroom>
      </room>
      <room id="1" caption="floor">
        <subroom id="1" caption="Room 2" class="Not specified" A_x="0" B_y="0" C_z="0">
          <polygon caption="wall">
            <vertex px="8" py="0"/>
            <vertex px="8" py="2"/>
          </polygon>
          <polygon caption="wall">
            <vertex px="8" py="5"/>
            <vertex px="8" py="3"/>
          </polygon>
          <polygon caption="wall">
            <vertex px="4" py="5"/>
            <vertex px="4" py="4"/>
          </polygon>
          <polygon caption="wall">
            <vertex px="4" py="3"/>
            <vertex px="4" py="2"/>
          </polygon>
          <polygon caption="wall">
            <vertex px="4" py="1"/>
            <vertex px="4" py="0"/>
          </polygon>
          <polygon caption="wall">
            <vertex px="4" py="5"/>
            <vertex px="8" py="5"/>
          </polygon>
          <polygon caption="wall">
            <vertex px="8" py="0"/>
            <vertex px="4" py="0"/>
          </polygon>
          <obstacle id="2" caption="Obstacle 2" closed="1">
            <polygon>
              <vertex px="6" py="3"/>
              <vertex px="5.5" py="2.5"/>
            </polygon>
            <polygon>
              <vertex px="5.5" py="2.5"/>
              <vertex px="5.5" py="2"/>
            </polygon>
            <polygon>
              <vertex px="5.5" py="2"/>
              <vertex px="6" py="1.5"/>
            </polygon>
            <polygon>
              <vertex px="6" py="1.5"/>
              <vertex px="6.5" py="1.5"/>
            </polygon>
            <polygon>
              <vertex px="6.5" py="1.5"/>
              <vertex px="7" py="2"/>
            </polygon>
            <polygon>
              <vertex px="7" py="2"/>
              <vertex px="7" py="2.5"/>
            </polygon>
            <polygon>
              <vertex px="7" py="2.5"/>
              <vertex px="6.5" py="3"/>
            </polygon>
            <polygon>
              <vertex px="6.5" py="3"/>
              <vertex px="6" py="3"/>
            </polygon>
          </obstacle>
        </subroom>
      </room>
      <room id="2" caption="floor">
        <subroom id="1" caption="Room 3" class="Not specified" A_x="0" B_y="0" C_z="0">
          <polygon caption="wall">
            <vertex px="8" py="0"/>
            <vertex px="8" py="2"/>
          </polygon>
          <polygon caption="wall">
            <vertex px="8" py="5"/>
            <vertex px="8" py="3"/>
          </polygon>
          <polygon caption="wall">
            <vertex px="8" py="5"/>
            <vertex px="11" py="4"/>
          </polygon>
          <polygon caption="wall">
            <vertex px="8" py="0"/>
            <vertex px="11" py="1"/>
          </polygon>
        </subroom>
      </room>
  </rooms>
  <transitions>
    <transition id="0" caption="exit" type="emergency" room1_id="2" subroom1_id="1" room2_id="-1" subroom2_id="-1">
      <vertex px="11" py="1"/>
      <vertex px="11" py="4"/>
    </transition>
    
    <transition id="1" caption="exit" type="emergency" room1_id="1" subroom1_id="1" room2_id="2" subroom2_id="1">
      <vertex px="8" py="2"/>
      <vertex px="8" py="3"/>
    </transition>
    <transition id="2" caption="exit" type="emergency" room1_id="0" subroom1_id="1" room2_id="1" subroom2_id="1">
      <vertex px="4" py="4"/>
      <vertex px="4" py="3"/>
    </transition>
    <transition id="3" caption="exit" type="emergency" room1_id="0" subroom1_id="1" room2_id="1" subroom2_id="1">
      <vertex px="4" py="2"/>
      <vertex px="4" py="1"/>          
    </transition>
  </transitions>
</geometry>
