=== PedestrianDynamics/jupedsim/xsd/jps_geometry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="geometry">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="rooms" maxOccurs="1" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="room" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="subroom" maxOccurs="unbounded" minOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="polygon" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="vertex" maxOccurs="unbounded" minOccurs="0">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:float" name="px" use="required" />
                                        <xs:attribute type="xs:float" name="py" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="caption" use="required" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="obstacle" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="polygon">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="vertex" maxOccurs="unbounded" minOccurs="0">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                              <xs:attribute type="xs:float" name="px" use="required" />
                                              <xs:attribute type="xs:float" name="py" use="required" />
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="caption" use="optional" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:int" name="id" use="required" />
                              <xs:attribute type="xs:string" name="caption" use="optional" />
                              <xs:attribute type="xs:float" name="height" use="optional" />
                              <xs:attribute type="xs:int" name="closed" use="optional" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="up" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:float" name="px" use="required" />
                                  <xs:attribute type="xs:byte" name="py" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="down" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:float" name="px" use="required" />
                                  <xs:attribute type="xs:byte" name="py" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:int" name="id" use="required" />
                        <xs:attribute type="xs:string" name="caption" use="optional" />
                        <xs:attribute type="xs:float" name="A_x" use="optional" />
                        <xs:attribute type="xs:float" name="B_y" use="optional" />
                        <xs:attribute type="xs:float" name="C" use="optional" />
                        <xs:attribute name="class" use="required">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="stair" />
                              <xs:enumeration value="subroom" />
                              <xs:enumeration value="floor" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="crossings" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="crossing" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="vertex" maxOccurs="unbounded" minOccurs="0">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:float" name="px" use="required" />
                                        <xs:attribute type="xs:float" name="py" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:int" name="id" use="required" />
                              <xs:attribute type="xs:int" name="subroom1_id" use="required" />
                              <xs:attribute type="xs:int" name="subroom2_id" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="id" use="required" />
                  <xs:attribute type="xs:string" name="caption" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="transitions">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="transition" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="vertex" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="px" use="required" />
                            <xs:attribute type="xs:float" name="py" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="id" use="required" />
                  <xs:attribute type="xs:string" name="caption" use="required" />
                  <xs:attribute type="xs:string" name="type" use="optional" />
                  <xs:attribute type="xs:int" name="room1_id" use="required" />
                  <xs:attribute type="xs:int" name="subroom1_id" use="required" />
                  <xs:attribute type="xs:int" name="room2_id" use="required" />
                  <xs:attribute type="xs:int" name="subroom2_id" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="caption" use="required" />
      <xs:attribute name="version" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:float">
            <xs:enumeration value="0.8" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="unit" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="m" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== PedestrianDynamics/jupedsim/inputfiles/events/hall/big_room_geo.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<geometry version="0.5" caption="test" unit="m" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="http://xsd.jupedsim.org/0.6/jps_geometry.xsd">
	<rooms>
		<room id="0" caption="hall">
			<subroom id="0" closed="0" class="subroom">
				<polygon caption="wall">
					<vertex px="0.0" py="18.0" />
					<vertex px="0.0" py="30.0" />
					<vertex px="12.0" py="30.0" />
				</polygon>
				<polygon caption="wall">
					<vertex px="18.0" py="30.0" />
					<vertex px="30.0" py="30.0" />
					<vertex px="30.0" py="18.0" />
				</polygon>
				<polygon caption="wall">
					<vertex px="30.0" py="12.0" />
					<vertex px="30.0" py="0.0" />
					<vertex px="18.0" py="0.0" />
				</polygon>
				<polygon caption="wall">
					<vertex px="12.0" py="0.0" />
					<vertex px="0.0" py="0.0" />
					<vertex px="0.0" py="12.0" />
				</polygon>
			</subroom>
		</room>
	</rooms>

	<transitions>
		<transition id="2" caption="exit" type="emergency"
			room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
			<vertex px="0.0" py="12.0" />
			<vertex px="0.0" py="18.0" />
		</transition>
		<transition id="3" caption="exit" type="emergency"
			room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
			<vertex px="12.0" py="30.0" />
			<vertex px="18.0" py="30.0" />
		</transition>
		<transition id="4" caption="exit" type="emergency"
			room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
			<vertex px="30.0" py="12.0" />
			<vertex px="30.0" py="18.0" />
		</transition>
		<transition id="5" caption="exit" type="emergency"
			room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
			<vertex px="12.0" py="0.0" />
			<vertex px="18.0" py="0.0" />
		</transition>
	</transitions>
</geometry>

=== PedestrianDynamics/jupedsim/Utest/rimea_tests/test_3/geometry.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<geometry version="0.5" caption="second life" unit="m" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/jps_geometry.xsd">
	<rooms>
		<room id="0" caption="ground floor">
			<subroom id="0" closed="0" class="subroom" A_x="0" B_y="0" C_z="6">
				<polygon caption="wall">
					<vertex px="0.0" py="2.0" />
					<vertex px="-2.0" py="2.0" />
					<vertex px="-2.0" py="0.0" />
					<vertex px="0.0" py="0.0" />
				</polygon>
			</subroom>

			<subroom id="1" closed="0" class="stair" A_x="-0.75" B_y="0" C_z="6">
				<polygon caption="wall">
					<vertex px="0.0" py="0.0" />
					<vertex px="8.0" py="0.0" />
				</polygon>
				<polygon caption="wall">
					<vertex px="0.0" py="2.0" />
					<vertex px="8.0" py="2.0" />
				</polygon>
				<up px="8.0" py="1.0" />
				<down px="0.0" py="1.0" />
			</subroom>
			<crossings>
				<crossing id="1" subroom1_id="0" subroom2_id="1">
					<vertex px="0.0" py="0.0" />
					<vertex px="0.0" py="2.0" />
				</crossing>
			</crossings>
		</room>

		<room id="1" caption="basement">
			<subroom id="0" closed="0" class="subroom" A_x="0" B_y="0" C_z="0">
				<polygon caption="wall">
					<vertex px="8.0" py="2.0" />
					<vertex px="10.0" py="2.0" />
				</polygon>
				<polygon caption="wall">
					<vertex px="8.0" py="0.0" />
					<vertex px="10.0" py="0.0" />
				</polygon>
			</subroom>
		</room>
	</rooms>

	<transitions>
		<transition id="2" caption="main exit" type="emergency" room1_id="1" subroom1_id="0" room2_id="-1" subroom2_id="-1">
			<vertex px="10.0" py="0.0" />
			<vertex px="10.0" py="2.0" />
		</transition>

		<transition id="3" caption="StairDown" type="emergency" room1_id="0" subroom1_id="1" room2_id="1" subroom2_id="0">
			<vertex px="8.0" py="0.0" />
			<vertex px="8.0" py="2.0" />
		</transition>
	</transitions>
</geometry>

=== PedestrianDynamics/jupedsim/systemtest/door_tests/test_flow_regulation/geometry.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<geometry version="0.8" caption="flow regulation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xsd.jupedsim.org/jps_geometry.xsd" unit="m">
    <rooms>
        <room id="0" caption="floor">
            <subroom id="1" caption="Room 1" class="Not specified" A_x="0" B_y="0" C_z="0">
                <polygon caption="wall">
                    <vertex px="0" py="0" />
                    <vertex px="0" py="10" />
                </polygon>
                <polygon caption="wall">
                    <vertex px="0" py="10" />
                    <vertex px="10" py="10" />
                </polygon>
                <polygon caption="wall">
                    <vertex px="10" py="10" />
                    <vertex px="10" py="5.5"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="10" py="4.5"/>
                    <vertex px="10" py="0" />
                </polygon>
                <polygon caption="wall">
                    <vertex px="10" py="0" />
                    <vertex px="0" py="0" />
                </polygon>
            </subroom>
            <crossings />
        </room>
    </rooms>
    <transitions>
        <transition id="0" caption="NaN" type="NaN" room1_id="0" subroom1_id="1" room2_id="-1" subroom2_id="-1">
            <vertex px="10" py="4.5"/>
            <vertex px="10" py="5.5"/>
        </transition>
    </transitions>
</geometry>

=== PedestrianDynamics/jupedsim/systemtest/router_tests/test_router_7/geometry.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<geometry version="0.8" caption="corner" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xsd.jupedsim.org/jps_geometry.xsd" unit="m">
    <rooms>
        <room id="0" caption="floor">
            <subroom id="1" caption="Room 1" class="Corridor" A_x="0" B_y="0" C_z="0">
                <polygon caption="wall">
                    <vertex px="14.12" py="0.92"/>
                    <vertex px="17.12" py="0.92"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="14.12" py="0.92"/>
                    <vertex px="14.12" py="1.92"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="14.12" py="10.32"/>
                    <vertex px="14.12" py="4.32"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="14.12" py="10.32"/>
                    <vertex px="17.12" py="10.32"/>
                </polygon>
            </subroom>
            <subroom id="2" caption="Room 2" class="Corridor" A_x="0" B_y="0" C_z="0">
                <polygon caption="wall">
                    <vertex px="2.12" py="1.92"/>
                    <vertex px="2.12" py="0.92"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="2.12" py="10.32"/>
                    <vertex px="-0.88" py="10.32"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="2.12" py="0.92"/>
                    <vertex px="-0.88" py="0.92"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="2.12" py="4.32"/>
                    <vertex px="2.12" py="10.32"/>
                </polygon>
            </subroom>
            <subroom id="3" caption="Room 3" class="Corridor" A_x="0" B_y="0" C_z="0">
                <polygon caption="wall">
                    <vertex px="8.12" py="0.92"/>
                    <vertex px="14.12" py="0.92"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="2.12" py="0.92"/>
                    <vertex px="8.12" py="0.92"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="14.12" py="0.92"/>
                    <vertex px="14.12" py="1.92"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="14.12" py="10.32"/>
                    <vertex px="14.12" py="4.32"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="2.12" py="1.92"/>
                    <vertex px="2.12" py="0.92"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="2.12" py="4.32"/>
                    <vertex px="2.12" py="10.32"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="8.12" py="10.32"/>
                    <vertex px="14.12" py="10.32"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="2.12" py="10.32"/>
                    <vertex px="8.12" py="10.32"/>
                </polygon>
                <obstacle id="0" caption="Obstacle 0" closed="1">
                    <polygon>
                        <vertex px="8.12" py="8.82"/>
                        <vertex px="8.12" py="9.82"/>
                    </polygon>
                    <polygon>
                        <vertex px="8.12" py="9.82"/>
                        <vertex px="8.27" py="9.82"/>
                    </polygon>
                    <polygon>
                        <vertex px="8.12" py="8.82"/>
                        <vertex px="8.27" py="8.82"/>
                    </polygon>
                    <polygon>
                        <vertex px="8.27" py="9.82"/>
                        <vertex px="8.27" py="8.82"/>
                    </polygon>
                </obstacle>
                <obstacle id="1" caption="Obstacle 1" closed="1">
                    <polygon>
                        <vertex px="8.12" py="7.82"/>
                        <vertex px="8.12" py="6.82"/>
                    </polygon>
                    <polygon>
                        <vertex px="8.12" py="7.82"/>
                        <vertex px="8.27" py="7.82"/>
                    </polygon>
                    <polygon>
                        <vertex px="8.12" py="6.82"/>
                        <vertex px="8.27" py="6.82"/>
                    </polygon>
                    <polygon>
                        <vertex px="8.27" py="7.82"/>
                        <vertex px="8.27" py="6.82"/>
                    </polygon>
                </obstacle>
                <obstacle id="2" caption="Obstacle 2" closed="1">
                    <polygon>
                        <vertex px="8.12" py="5.82"/>
                        <vertex px="8.12" py="3.82"/>
                    </polygon>
                    <polygon>
                        <vertex px="8.12" py="5.82"/>
                        <vertex px="8.27" py="5.82"/>
                    </polygon>
                    <polygon>
                        <vertex px="8.12" py="3.82"/>
                        <vertex px="8.27" py="3.82"/>
                    </polygon>
                    <polygon>
                        <vertex px="8.27" py="5.82"/>
                        <vertex px="8.27" py="3.82"/>
                    </polygon>
                </obstacle>
                <obstacle id="3" caption="Obstacle 3" closed="1">
                    <polygon>
                        <vertex px="8.12" py="2.82"/>
                        <vertex px="8.12" py="1.32"/>
                    </polygon>
                    <polygon>
                        <vertex px="8.12" py="2.82"/>
                        <vertex px="8.27" py="2.82"/>
                    </polygon>
                    <polygon>
                        <vertex px="8.27" py="2.82"/>
                        <vertex px="8.27" py="1.32"/>
                    </polygon>
                    <polygon>
                        <vertex px="8.27" py="1.32"/>
                        <vertex px="8.12" py="1.32"/>
                    </polygon>
                </obstacle>
            </subroom>
            <crossings>
                <crossing id="1" subroom1_id="1" subroom2_id="3">
                    <vertex px="14.12" py="1.92"/>
                    <vertex px="14.12" py="4.32"/>
                </crossing>
                <crossing id="3" subroom1_id="2" subroom2_id="3">
                    <vertex px="2.12" py="4.32"/>
                    <vertex px="2.12" py="1.92"/>
                </crossing>
            </crossings>
        </room>
    </rooms>
    <transitions>
        <transition id="0" caption="NaN" type="NaN" room1_id="0" subroom1_id="1" room2_id="-1" subroom2_id="-1">
            <vertex px="17.12" py="10.32"/>
            <vertex px="17.12" py="0.92"/>
        </transition>
        <transition id="1" caption="NaN" type="NaN" room1_id="0" subroom1_id="2" room2_id="-1" subroom2_id="-1">
            <vertex px="-0.88" py="10.32"/>
            <vertex px="-0.88" py="0.92"/>
        </transition>
    </transitions>
</geometry>

=== PedestrianDynamics/jupedsim/systemtest/router_tests/test_router_5/geometry.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<geometry version="0.8" caption="Basigo2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xsd.jupedsim.org/jps_geometry.xsd" unit="m">
    <rooms>
        <room id="0" caption="hall">
            <subroom id="0">
                <polygon caption="westwall1">
                    <vertex px="0.0" py="0.0"/>
                    <vertex px="0.0" py="4.0"/>
                </polygon>
                <polygon caption="westwall2">
                    <vertex px="0.0" py="4.8"/>
                    <vertex px="0.0" py="8.8"/>
                </polygon>
                <polygon caption="nortwall1">
                    <vertex px="0.0" py="8.8"/>
                    <vertex px="4.0" py="8.8"/>
                </polygon>
                <polygon caption="northwall2">
                    <vertex px="4.8" py="8.8"/>
                    <vertex px="8.8" py="8.8"/>
                </polygon>
                <polygon caption="eastwall1">
                    <vertex px="8.8" py="8.8"/>
                    <vertex px="8.8" py="4.8"/>
                </polygon>
                <polygon caption="eastwall2">
                    <vertex px="8.8" py="4.0"/>
                    <vertex px="8.8" py="0.0"/>
                </polygon>
                <polygon caption="southwall1">
                    <vertex px="0.0" py="0.0"/>
                    <vertex px="4.0" py="0.0"/>
                </polygon>
                <polygon caption="southwall2">
                    <vertex px="4.8" py="0.0"/>
                    <vertex px="8.8" py="0.0"/>
                </polygon>
            </subroom>
        </room>
        <crossings/>
    </rooms>
    <transitions>
        <transition id="1" caption="exit west" type="emergency" room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
            <vertex px="0.0" py="4.0"/>
            <vertex px="0.0" py="4.8"/>
        </transition>
        <transition id="2" caption="exit north" type="emergency" room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
            <vertex px="4" py="8.8"/>
            <vertex px="4.8" py="8.8"/>
        </transition>
        <transition id="3" caption="exit east" type="emergency" room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
            <vertex px="8.8" py="4.8"/>
            <vertex px="8.8" py="4.0"/>
        </transition>
        <transition id="4" caption="exit south" type="emergency" room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
            <vertex px="4" py="0.0"/>
            <vertex px="4.8" py="0.0"/>
        </transition>
    </transitions>
</geometry>
