=== PedestrianDynamics/jupedsim/xsd/jps_geometry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="geometry">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="rooms" maxOccurs="1" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="room" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="subroom" maxOccurs="unbounded" minOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="polygon" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="vertex" maxOccurs="unbounded" minOccurs="0">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:float" name="px" use="required" />
                                        <xs:attribute type="xs:float" name="py" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="caption" use="required" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="obstacle" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="polygon">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="vertex" maxOccurs="unbounded" minOccurs="0">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                              <xs:attribute type="xs:float" name="px" use="required" />
                                              <xs:attribute type="xs:float" name="py" use="required" />
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="caption" use="optional" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:int" name="id" use="required" />
                              <xs:attribute type="xs:string" name="caption" use="optional" />
                              <xs:attribute type="xs:float" name="height" use="optional" />
                              <xs:attribute type="xs:int" name="closed" use="optional" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="up" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:float" name="px" use="required" />
                                  <xs:attribute type="xs:byte" name="py" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="down" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:float" name="px" use="required" />
                                  <xs:attribute type="xs:byte" name="py" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:int" name="id" use="required" />
                        <xs:attribute type="xs:string" name="caption" use="optional" />
                        <xs:attribute type="xs:float" name="A_x" use="optional" />
                        <xs:attribute type="xs:float" name="B_y" use="optional" />
                        <xs:attribute type="xs:float" name="C" use="optional" />
                        <xs:attribute name="class" use="required">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="stair" />
                              <xs:enumeration value="subroom" />
                              <xs:enumeration value="floor" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="crossings" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="crossing" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="vertex" maxOccurs="unbounded" minOccurs="0">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:float" name="px" use="required" />
                                        <xs:attribute type="xs:float" name="py" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:int" name="id" use="required" />
                              <xs:attribute type="xs:int" name="subroom1_id" use="required" />
                              <xs:attribute type="xs:int" name="subroom2_id" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="id" use="required" />
                  <xs:attribute type="xs:string" name="caption" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="transitions">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="transition" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="vertex" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:float" name="px" use="required" />
                            <xs:attribute type="xs:float" name="py" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="id" use="required" />
                  <xs:attribute type="xs:string" name="caption" use="required" />
                  <xs:attribute type="xs:string" name="type" use="optional" />
                  <xs:attribute type="xs:int" name="room1_id" use="required" />
                  <xs:attribute type="xs:int" name="subroom1_id" use="required" />
                  <xs:attribute type="xs:int" name="room2_id" use="required" />
                  <xs:attribute type="xs:int" name="subroom2_id" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="caption" use="required" />
      <xs:attribute name="version" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:float">
            <xs:enumeration value="0.8" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="unit" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="m" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== PedestrianDynamics/jupedsim/demos/08_sources/source_geo.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<geometry version="0.8" caption="hybrid test" unit="m" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xsd.jupedsim.org/0.6/jps_geometry.xsd">
  <rooms>
    <room id="0" caption="hall0">
      <subroom id="0" closed="0" class="floor">
        <polygon caption="wall">
          <vertex px="0.0" py="2.8" />
          <vertex px="0.0" py="0.0" />
          <vertex px="3.6" py="0.0" />
        </polygon>
        <polygon caption="wall">
          <vertex px="5.2" py="0.0" />
          <vertex px="9.2" py="0.0" />
          <vertex px="9.2" py="2.8" />
        </polygon>
        <polygon caption="wall">
          <vertex px="9.2" py="6.4" />
          <vertex px="9.2" py="9.2" />
          <vertex px="5.6" py="9.2" />
        </polygon>
        <polygon caption="wall">
          <vertex px="3.2" py="9.2" />
          <vertex px="0.0" py="9.2" />
          <vertex px="0.0" py="6.4" />
        </polygon>
      </subroom>
    </room>
    <room id="1" caption="hall1">
      <subroom id="0" closed="0" class="floor">
        <polygon caption="wall">
          <vertex px="3.6" py="-2.0" />
          <vertex px="3.6" py="0.0" />
        </polygon>
        <polygon caption="wall">
          <vertex px="5.2" py="-2.0" />
          <vertex px="5.2" py="0.0" />
        </polygon>
      </subroom>
    </room>
    <room id="2" caption="hall2">
      <subroom id="0" closed="0" class="floor">
        <polygon caption="wall">
          <vertex px="9.2" py="2.8" />
          <vertex px="13.2" py="2.8" />
        </polygon>
        <polygon caption="wall">
          <vertex px="9.2" py="6.4" />
          <vertex px="13.2" py="6.4" />
        </polygon>
      </subroom>
      <subroom id="1" closed="0" class="floor">
        <polygon caption="wall">
          <vertex px="13.2" py="2.8" />
          <vertex px="17.2" py="2.8" />
        </polygon>
        <polygon caption="wall">
          <vertex px="13.2" py="6.4" />
          <vertex px="17.2" py="6.4" />
        </polygon>
      </subroom>
      <crossings>
	<crossing id="0" subroom1_id="0" subroom2_id="1">
	  <vertex px="13.2" py="2.8" /> 
	  <vertex px="13.2" py="6.4" />
	</crossing> 
      </crossings>
    </room>
    <room id="3" caption="hall3">
      <subroom id="0" closed="0" class="floor">
        <polygon caption="wall">
          <vertex px="3.2" py="9.2" />
          <vertex px="3.2" py="11.2" />
        </polygon>
        <polygon caption="wall">
          <vertex px="5.6" py="9.2" />
          <vertex px="5.6" py="11.2" />
        </polygon>
      </subroom>
    </room>
    <room id="4" caption="hall4">
      <subroom id="0" closed="0" class="floor">
        <polygon caption="wall">
          <vertex px="0.0" py="2.8" />
          <vertex px="-2.0" py="2.8" />
        </polygon>
        <polygon caption="wall">
          <vertex px="0.0" py="6.4" />
          <vertex px="-2.0" py="6.4" />
        </polygon>
      </subroom>
    </room>
  </rooms>

  <transitions>
    <transition id="0" caption="exit" type="emergency" room1_id="0" subroom1_id="0" room2_id="1" subroom2_id="0">
      <vertex px="3.6" py="0.0" />
      <vertex px="5.2" py="0.0" />
    </transition>
    <transition id="1" caption="exit" type="emergency" room1_id="0" subroom1_id="0" room2_id="2" subroom2_id="0">
      <vertex px="9.2" py="2.8" />
      <vertex px="9.2" py="6.4" />
    </transition>
    <transition id="2" caption="exit" type="emergency" room1_id="0" subroom1_id="0" room2_id="3" subroom2_id="0">
      <vertex px="3.2" py="9.2" />
      <vertex px="5.6" py="9.2" />
    </transition>
    <transition id="3" caption="exit" type="emergency" room1_id="0" subroom1_id="0" room2_id="4" subroom2_id="0">
      <vertex px="0.0" py="2.8" />
      <vertex px="0.0" py="6.4" />
    </transition>
    <transition id="4" caption="exit" type="emergency" room1_id="1" subroom1_id="0" room2_id="-1" subroom2_id="-1">
      <vertex px="3.6" py="-2.0" />
      <vertex px="5.20" py="-2.0" />
    </transition>
    <transition id="5" caption="exit" type="emergency" room1_id="2" subroom1_id="1" room2_id="-1" subroom2_id="-1">
      <vertex px="17.2" py="2.8" />
      <vertex px="17.2" py="6.4" />
    </transition>
    <transition id="6" caption="exit" type="emergency" room1_id="3" subroom1_id="0" room2_id="-1" subroom2_id="-1">
      <vertex px="3.2" py="11.2" />
      <vertex px="5.6" py="11.2" />
    </transition>
    <transition id="7" caption="exit" type="emergency" room1_id="4" subroom1_id="0" room2_id="-1" subroom2_id="-1">
      <vertex px="-2.0" py="2.8" />
      <vertex px="-2.0" py="6.4" />
    </transition>
  </transitions>
</geometry>

=== PedestrianDynamics/jupedsim/systemtest/Validation/7test_BO/geometry.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<geometry version="0.8" caption="corner" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xsd.jupedsim.org/jps_geometry.xsd" unit="m">
    <rooms>
        <room id="0" caption="hall">
            <subroom id="0" caption="Room 0" class="subroom">
                <polygon caption="wall">
                    <vertex px="10.1775" py="17.4988"/>
                    <vertex px="5.17747" py="17.4988"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="5.17747" py="17.4988"/>
                    <vertex px="5.17747" py="13.8988"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="5.17747" py="13.8988"/>
                    <vertex px="10.1775" py="13.8988"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="14.1775" py="17.4988"/>
                    <vertex px="22.1775" py="17.4988"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="14.1775" py="13.8988"/>
                    <vertex px="22.1775" py="13.8988"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="26.1775" py="17.4988"/>
                    <vertex px="31.1775" py="17.4988"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="26.1775" py="13.8988"/>
                    <vertex px="31.1775" py="13.8988"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="31.1775" py="17.4988"/>
                    <vertex px="31.1775" py="13.8988"/>
                </polygon>
            </subroom>
            <crossings/>
        </room>
    </rooms>
    <transitions>
        <transition id="0" caption="lefttop" type="emergency" room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
            <vertex px="10.1775" py="17.4988"/>
            <vertex px="14.1775" py="17.4988"/>
        </transition>
        <transition id="1" caption="leftbottom" type="emergency" room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
            <vertex px="10.1775" py="13.8988"/>
            <vertex px="14.1775" py="13.8988"/>
        </transition>
        <transition id="2" caption="righttop" type="emergency" room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
            <vertex px="22.1775" py="17.4988"/>
            <vertex px="26.1775" py="17.4988"/>
        </transition>
        <transition id="3" caption="rightbottom" type="emergency" room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
            <vertex px="22.1775" py="13.8988"/>
            <vertex px="26.1775" py="13.8988"/>
        </transition>
    </transitions>
</geometry>

=== PedestrianDynamics/jupedsim/Utest/rimea_tests/test_11/geometry.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<geometry version="0.5" caption="second life" unit="m"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../../xsd/jps_geometry.xsd">
  <rooms>
    <room id="0" caption="hall">
      <subroom id="0" closed="0" class="subroom">
	<polygon caption="wall">
	  <vertex px="28.0" py="20.0" />
	  <vertex px="30.0" py="20.0" />
	  <vertex px="30.0" py="0.0" />
	  <vertex px="0.0" py="0.0" />
	  <vertex px="0.0" py="20.0" />
	  <vertex px="21.0" py="20.0" />
	</polygon>
	<polygon caption="wall_doors">
	  <vertex px="22.0" py="20.0" />
	  <vertex px="27.0" py="20.0" />
	</polygon>
	<!-- <polygon caption="wall_doors2"> -->
	<!--   <vertex px="21.0" py="20.0" /> -->
	<!--   <vertex px="21.0" py="20.5" /> -->
	<!-- </polygon> -->
        <!-- <polygon caption="wall_doors3"> -->
        <!--   <vertex px="22.0" py="20.0" /> -->
	<!--   <vertex px="22.0" py="20.5" /> -->
	<!-- </polygon> -->
        <!-- <polygon caption="wall_doors4"> -->
        <!--   <vertex px="27.0" py="20.0" /> -->
	<!--   <vertex px="27.0" py="20.5" /> -->
	<!-- </polygon> -->
        <!-- <polygon caption="wall_doors5"> -->
        <!--   <vertex px="28.0" py="20.0" /> -->
	<!--   <vertex px="28.0" py="20.5" /> -->
	<!-- </polygon> -->
      </subroom>
    </room>
   
  </rooms>

  <transitions>
    <!-- exits like crossings but between rooms or to outside (room with index
	 = -1) -->
    <transition id="0" caption="exit_1" type="emergency"
		room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
      <vertex px="21.0" py="20.0" />
      <vertex px="22.0" py="20.0" />
    </transition>
    
    <transition id="1" caption="exit_2" type="emergency"
		room1_id="0" subroom1_id="0" room2_id="-1" subroom2_id="-1">
      <vertex px="27.0" py="20.0" />
      <vertex px="28.0" py="20.0" />
    </transition>
    
  </transitions>
</geometry>

=== PedestrianDynamics/jupedsim/jpsreport/demos/crossing/geo_crossing_90_c_6_v5.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<geometry version ="0.8" caption="second life" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xsd.jupedsim.org/jps_geometry.xsd" unit="m">
	<rooms>
		<room id="0" caption="hall" zpos="0.00">
			<subroom id="0" closed="0" class="subroom">
				<polygon caption="wall">
					<vertex px="0.0" py="0.0"/>
					<vertex px="0.0" py="-1.00"/>
					<vertex px="4.00" py="-1.00"/>
					<vertex px="4.00" py="0.0"/>
					<vertex px="6.50" py="0.0"/>
					<vertex px="6.50" py="4.00"/>
					<vertex px="4.00" py="4.00"/>
					<vertex px="4.00" py="5.00"/>
					<vertex px="0.0" py="5.00"/>
					<vertex px="0.0" py="4.00"/>
					<vertex px="-4.00" py="4.00"/>
					<vertex px="-4.00" py="0.0"/> 	
					<vertex px="0.0" py="0.0"/>					
				</polygon>
				<obstacle id="1" caption="table" height="1.0" closed="1">
					<polygon>
						<vertex px="2.08" py="2.30"/>
						<vertex px="2.22" py="2.22"/>
						<vertex px="2.30" py="2.08"/>
						<vertex px="2.30" py="1.92"/>
						<vertex px="2.22" py="1.79"/>
						<vertex px="2.08" py="1.70"/>	
						<vertex px="1.92" py="1.70"/>	
						<vertex px="1.78" py="1.78"/>	
						<vertex px="1.70" py="1.92"/>	
						<vertex px="1.70" py="2.08"/>	
						<vertex px="1.78" py="2.22"/>	
						<vertex px="1.92" py="2.30"/>	
						<vertex px="2.08" py="2.30"/>
					</polygon>
				</obstacle>			
			</subroom>
		</room>
	</rooms>
</geometry>

=== PedestrianDynamics/jupedsim/jpsreport/Utest/Methods/geo_Methods_subrooms.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<geometry version="0.8" caption="corner" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xsd.jupedsim.org/jps_geometry.xsd" unit="m">
    <rooms>
        <room id="0" caption="hall">
          <subroom id="1" caption="Room 1" class="Hall" A_x="0" B_y="0" C_z="0">
                <polygon caption="wall">
                  <vertex px=" 0.0" py=" 0.0"/>
                  <vertex px=" 0.0" py="20.0"/>
                </polygon>
              <polygon caption="wall">
                  <vertex px=" 0.0" py="20.0"/>
                  <vertex px="20.0" py="20.0"/>
              </polygon>
              <polygon caption="wall">
                  <vertex px="20.0" py="20.0"/>
                  <vertex px="20.0" py="10.5"/>
              </polygon>
              <polygon caption="wall">
                  <vertex px="20.0" py=" 9.5"/>
                  <vertex px="20.0" py=" 0.0"/>
              </polygon>
              <polygon caption="wall">
                  <vertex px="20.0" py=" 0.0"/>
                  <vertex px=" 0.0" py=" 0.0"/>
              </polygon>
          </subroom>
          <subroom id="2" caption="Room 2" class="Hall" A_x="0" B_y="0" C_z="0">
              <polygon caption="wall">
                  <vertex px="20.0" py="10.5"/>
                  <vertex px="28.0" py="10.5"/>
              </polygon>
              <polygon caption="wall">
                  <vertex px="28.0" py=" 9.5"/>
                  <vertex px="20.0" py=" 9.5"/>
              </polygon>
          </subroom>
          <subroom id="3" caption="Room 2" class="Hall" A_x="0" B_y="0" C_z="0">
              <polygon caption="wall">
                  <vertex px="28.0" py="10.5"/>
                  <vertex px="28.0" py="20.0"/>
              </polygon>
              <polygon caption="wall">
                  <vertex px="28.0" py="20.0"/>
                  <vertex px="48.0" py="20.0"/>
              </polygon>
              <polygon caption="wall">
                  <vertex px="48.0" py="20.0"/>
                  <vertex px="48.0" py="11.0"/>
              </polygon>
              <polygon caption="wall">
                  <vertex px="48.0" py=" 9.0"/>
                  <vertex px="48.0" py=" 0.0"/>
              </polygon>
              <polygon caption="wall">
                  <vertex px="48.0" py=" 0.0"/>
                  <vertex px="28.0" py=" 0.0"/>
              </polygon>
              <polygon caption="wall">
                  <vertex px="28.0" py=" 0.0"/>
                  <vertex px="28.0" py=" 9.5"/>
              </polygon>
          </subroom>

          <crossings>
            <crossing id="0" subroom1_id ="1" subroom2_id ="2">
                <vertex px=" 20.0 " py=" 9.5 "/>
                <vertex px=" 20.0 " py="10.5 "/>
            </crossing>
            <crossing id="1" subroom1_id ="2" subroom2_id ="3">
              <vertex px=" 28.0 " py=" 9.5 "/>
              <vertex px=" 28.0 " py="10.5 "/>
            </crossing>
          </crossings>

        </room>
    </rooms>

    <transitions>
      <transition id="0" caption="NaN" type="NaN" room1_id="0" subroom1_id="3" room2_id="-1" subroom2_id="-1">
        <vertex px="48.0" py=" 9.0"/>
        <vertex px="48.0" py="11.0"/>
      </transition>
    </transitions>

</geometry>

=== PedestrianDynamics/jupedsim/systemtest/test_geometry/clean_geometry/geometry9-2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<geometry version="0.8" caption="corner" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xsd.jupedsim.org/jps_geometry.xsd" unit="m">
    <rooms>
        <room id="1" caption="floor">
            <subroom id="1" caption="Room 1" class="Not specified" A_x="0" B_y="0" C_z="0">
                <polygon caption="wall">
                    <vertex px="0" py="4"/>
                    <vertex px="0" py="8"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="0" py="6"/>
                    <vertex px="-2" py="6"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="-2" py="6"/>
                    <vertex px="-2" py="4"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="-2" py="4"/>
                    <vertex px="2" py="4"/>
                </polygon>
            </subroom>
            <crossings/>
        </room>
        <room id="2" caption="floor">
            <subroom id="2" caption="Room 2" class="Not specified" A_x="0" B_y="0" C_z="0">
                <polygon caption="wall">
                    <vertex px="0" py="4"/>
                    <vertex px="2" py="6"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="0" py="4"/>
                    <vertex px="0" py="8"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="0" py="6"/>
                    <vertex px="2" py="6"/>
                </polygon>
            </subroom>
            <crossings/>
        </room>
        <room id="3" caption="floor">
            <subroom id="3" caption="Room 3" class="Not specified" A_x="0" B_y="0" C_z="0">
                <polygon caption="wall">
                    <vertex px="0" py="4"/>
                    <vertex px="0" py="8"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="0" py="8"/>
                    <vertex px="2" py="8"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="2" py="8"/>
                    <vertex px="2" py="6"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="0" py="6"/>
                    <vertex px="2" py="6"/>
                </polygon>
            </subroom>
            <crossings/>
        </room>
        <room id="4" caption="floor">
            <subroom id="4" caption="Room 4" class="Not specified" A_x="0" B_y="0" C_z="0">
                <polygon caption="wall">
                    <vertex px="0" py="4"/>
                    <vertex px="2" py="6"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="-2" py="4"/>
                    <vertex px="2" py="4"/>
                </polygon>
                <polygon caption="wall">
                    <vertex px="2" py="4"/>
                    <vertex px="2" py="6"/>
                </polygon>
            </subroom>
            <crossings/>
        </room>
    </rooms>
    
    <transitions>
        <transition id="1" caption="exit1" type="NaN" room1_id="1" subroom1_id="1" room2_id="-1" subroom2_id="-1">
            <vertex px="-2" py="4.5"/>
            <vertex px="-2" py="5.5"/>
        </transition>
        <transition id="2" caption="exit2" type="NaN" room1_id="3" subroom1_id="3" room2_id="-1" subroom2_id="-1">
            <vertex px="0.5" py="8"/>
            <vertex px="1.5" py="8"/>
        </transition>
        
        <transition id="3" caption="cross1" type="NaN" room1_id="1" subroom1_id="1" room2_id="2" subroom2_id="2">
            <vertex px="0" py="4.5"/>
            <vertex px="0" py="5.5"/>
        </transition>
        <transition id="4" caption="cross2" type="NaN" room1_id="2" subroom1_id="2" room2_id="3" subroom2_id="3">
            <vertex px="0.5" py="6"/>
            <vertex px="1.5" py="6"/>
        </transition>
        <transition id="5" caption="cross3" type="NaN" room1_id="2" subroom1_id="2" room2_id="4" subroom2_id="4">
            <vertex px="0.5" py="4.5"/>
            <vertex px="1.5" py="5.5"/>
        </transition>
    </transitions>
</geometry>
